### ISSUE TITLE
Could not load type UserInfo

### ISSUE THREAD

**Issue by andyunsarcus** [developerforce/Force.com-Toolkit-for-NET#123]
I have a project which uses the toolkit to authenticate with Salesforce. It works fine locally but when I deploy to a server I get an error from the below code :

Task<Salesforce.Common.Models.UserInfo> getUserTask = Task.Run(() => client.UserInfo<Salesforce.Common.Models.UserInfo>(userURl));
                getUserTask.Wait();

The errors are below :

System.AggregateException: One or more errors occurred. ---> System.TypeLoadException: Could not load type '<UserInfo>d__f`1' from assembly 'Salesforce.Force, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Salesforce.Force.ForceClient.<UserInfo>d__f`1.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Salesforce.Force.ForceClient.UserInfo[T](String url)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at IndigoAdmin.Controllers.AccountController.SFLogin(String code)
---> (Inner Exception #0) System.TypeLoadException: Could not load type '<UserInfo>d__f`1' from assembly 'Salesforce.Force, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Salesforce.Force.ForceClient.<UserInfo>d__f`1.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Salesforce.Force.ForceClient.UserInfo[T](String url)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

Any ideas ?

**Comment by wadewegner** [comment]
No idea. Is there a reason you're executing it this way? Perhaps something about your server and the way it's executing Task?

Let us know if this is still an issue. Ideally detailed steps on how to reproduce it. Thanks!

**Comment by andyunsarcus** [comment]
You've taken such a long time to reply, that I've rewritten the code to work a different way.

**Comment by mreyeros** [comment]
I am seeing a similar issue on my end while using the toolkit.  In my local development environment all works well, once deployed to one of our servers I receive the following error when attempting to get a list of records back from SF.  The code I am calling looks like this:

public async Task<List<CommunityContact>> GetCommunityContacts(string communityAccountId)
        {
            var auth = await Login();

            var client = new ForceClient(auth.InstanceUrl, auth.AccessToken, auth.ApiVersion);

            var query =
                "SELECT Id, Title, FirstName, LastName, Phone, Fax, Email, Active__c, Regional_Manager_Indicator__c " +
                "FROM contact " +
                "WHERE ID IN(SELECT contact__C " +
                "               FROM account_relationship__c " +
                "WHERE account__C = '" + communityAccountId + "')";

            var queryResults = await client.QueryAllAsync<CommunityContact>(query);

            return queryResults.Records;
        }

Could not load type '<HttpGetAsync>d__7`1' from assembly 'Salesforce.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=9f7864e53fb79388' due to value type mismatch.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.TypeLoadException: Could not load type '<HttpGetAsync>d__7`1' from assembly 'Salesforce.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=9f7864e53fb79388' due to value type mismatch.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 


[TypeLoadException: Could not load type '<HttpGetAsync>d__7`1' from assembly 'Salesforce.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=9f7864e53fb79388' due to value type mismatch.]
   Salesforce.Common.<HttpGetAsync>d__7`1.MoveNext() +0
   System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start(TStateMachine& stateMachine) +70
   System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start(TStateMachine& stateMachine) +60
   Salesforce.Common.ServiceHttpClient.HttpGetAsync(String urlSuffix) +295
   Salesforce.Force.ForceClient.QueryAsync(String query) +267
   MFH.Service.SalesForce.<GetCommunityContacts>d__e.MoveNext() in e:\Builds\39\ASP.PMSWebIT-Projects\mfh.assurant.com-dev\src\Multi Family Housing\MFH.Service\src\main\MFH.Service\SalesForce\SalesForceService.cs:67
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +59
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +25
   mfh.assurant.com.Features.Community.<GetContacts>d__0.MoveNext() in e:\Builds\39\ASP.PMSWebIT-Projects\mfh.assurant.com-dev\src\Multi Family Housing\mfh.assurant.com\src\dev\mfh.assurant.com\Features\Community\CommunityController.cs:30
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +59
   System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult) +84
   System.Web.Mvc.Async.<>c__DisplayClass37.<BeginInvokeAsynchronousActionMethod>b__36(IAsyncResult asyncResult) +17
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +32
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +50
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +225
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +225
   System.Web.Mvc.Async.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +34
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +26
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +100
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +13
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +36
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +54
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +39
   System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +12
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +28
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +54
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +29
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +21
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +36
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +54
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +31
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar) +129
