### ISSUE TITLE
BulkForceClient on nuget

### ISSUE THREAD

**Issue by avesse** [developerforce/Force.com-Toolkit-for-NET#246]
We've got the latest version of the nuget package installed (1.3.2) but can't find the `BulkForceClient` in there. Is the nuget package out of date?

**Comment by avesse** [comment]
(Also couldn't find it with a search in the repo, so not sure what code the readme is referring to...?)

**Comment by mp3tobi** [comment]
It's at the moment only a beta version: https://www.nuget.org/packages/DeveloperForce.Force/1.4.0-beta
But I don't know how to install this beta via nuget. :(

**Comment by rdev5** [comment]
I'm in the process of writing my own BulkForceClient as well.

Seems to be unimplemented in ForceToolkitForNet at this time as their [JobInfo class](https://github.com/developerforce/Force.com-Toolkit-for-NET/blob/master/src/CommonLibrariesForNET/Models/Xml/JobInfo.cs#L18) only contains a fraction of what the actual documentation specifies: https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/asynch_api_reference_jobinfo.htm

**Comment by rdev5** [comment]
Done: https://gist.github.com/rdev5/df5c5b3c359a9758c40d031363576b90

For now at least - I'm able to create batch upsert jobs, specifying which field will be my `externalId`. The primary "enabler" for being able to create this was to expose `_xmlHttpClient` and `_jsonHttpClient` as `protected` in `ForceClient.cs` [here](https://gist.github.com/rdev5/df5c5b3c359a9758c40d031363576b90#file-forceclient-cs-L16-L17)

**Comment by cemerson** [comment]
Are we sure BulkConstants is in 1.4.0-beta? I've got that installed in my project but can't find/use BulkConstants, CreateJobAsync etc. However if I clone the latest master branch from github and reference it that way in my project i *DO* see it. Unfortunately for some reason when I reference the full code/branch this way my web app hangs on any Salesforce connection then so I can't use this method for now. Which is why I'm trying to find out how/if we can get BulkConstants via nuget right now or not.

**Comment by wadewegner** [comment]
If this is still an issue (see latest updates to code) please re-open with more specifics.
