### ISSUE TITLE
External Id for Bulk Upserts

### ISSUE THREAD

**Issue by grahamthesmith** [developerforce/Force.com-Toolkit-for-NET#273]
Is it possible to provide a custom/external field name when performing bulk upserts, like you can when doing individual upserts:

        `public Task<SuccessResponse> UpsertExternalAsync(string objectName, string externalFieldName, string externalId, object record)`

**Comment by grahamthesmith** [comment]
For anyone else looking for a solution to this, you just need to add externalIdFieldName into the JobInfo:

```
    public class JobInfo
    {
        [XmlElement(ElementName = "operation")]
        public string Operation { get; set; }

        [XmlElement(ElementName = "object")]
        public string Object { get; set; }

		[XmlElement(ElementName = "externalIdFieldName")]
		public string externalIdFieldName { get; set; }

		[XmlElement(ElementName = "contentType")]
        public string ContentType { get; set; }

    }
```
And then populate it wherever you need to use it:


```
			var jobInfo = new JobInfo
			{
				ContentType = "XML",
				Object = objectName,
				externalIdFieldName = externalIdFieldName,
				Operation = operationType.Value()
			};
```
See [(https://salesforce.stackexchange.com/questions/14740/how-to-perform-upsert-in-salesforce-bulk-api)]

**Comment by pandreason** [comment]
@grahamthesmith  So , you are suggesting that we fork the repo if we want to actually be able to use the bulk upsert functionality that appears to be exposed by this repo?

**Comment by grahamthesmith** [comment]
You only need to do this if you are using a custom id field. If you need to use a custom id field then yes just add code as described to the JobInfo.

**Comment by pandreason** [comment]
This is just my opinion, but I think the right thing is not to expose the upsert functionality at all since the Salesforce Bulk Api Upsert requires the External ID and is therefore useless in the current implementation. Another solution would be to make a bulk operation method for operations where you want to use an externalId since sometimes you won't want to use the eternalID. Editing the jobinfo object has the effect of requiring the use of externalID on all bulk operations in the given implementation.
