### ISSUE TITLE
RunJobAndPollAsync - Hitting Insert Limit

### ISSUE THREAD

**Issue by StephenDoherty** [developerforce/Force.com-Toolkit-for-NET#406]
Hello,

I seem to be hitting a limit on the records inserting when I use the RunJobAndPollAsync method. I must be missing something or setting somewhere. (SFDC or VS). I have simplified my code below but, basically I am feeding in the SObject recordlist that has 957 records in it but it only loads 800 records. AM I missing a batch size or number of batch setting or something? Is there a limit I am missing. There are no errors i just skips any record past 800 and loads the rest successfully.

Thanks for any help.

```
var dtInvToInsertSFDC = new SObjectList<SObject> { };
dtInvToInsertSFDC.Add(new SObject {
                                                    { "Name", row["Prodcode"] },
                                                    { "Cease_Ship_Date__c", row["CeaseShipDate"] },
                                                    { "Company__c", row["Company"] },
                                                    { "Division__c", row["division"] },
                                                    { "Expiration_Date__c", row["expdt"] },
                                                    { "Lot_Number__c", row["Lot Number"] },
                                                    { "Product_Name__c", row["Prodname"] },
                                                    { "Quantity__c", row["Quantity"] },
                                                    { "Sample_Package_Size__c", row["Sample Package Size"] },
                                                    { "Status__c", row["status"] },
                                                    { "Warehouse_Location__c", row["WarehouseLoc"] },
                                                    { "Weight__c", row["Weight"] },
                                                    { "Bulk_or_Shelf_Stock__c", row["BulkOrShelfStock"] }
                                                     });                            
 if (dtInvToInsertSFDC.Count > 0)
 {                        
    //Insert new records                           
    var results = await client.RunJobAndPollAsync("Sample_Inventory__c", BulkConstants.OperationType.Insert, new List<SObjectList<SObject>> { dtInvToInsertSFDC });                        
    BatchResultErrorCheck(results);
}            
```

**Comment by Zhaph** [comment]
How long is it taking to process the batch? I think this is still using the original Bulk API (rather than Bulk API 2.0), so the following notes apply:

https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/asynch_api_concepts_limits.htm

> Batches are processed in chunks. The chunk size depends on the API version. In API version 20.0 and earlier, the chunk size is 100 records. In API version 21.0 and later, the chunk size is 200 records. There’s a 5-minute limit for processing each chunk. Also, if it takes longer than 10 minutes to process a whole batch, the Bulk API places the remainder of the batch back in the queue for later processing. If the Bulk API continues to exceed the 10-minute limit on subsequent attempts, the batch is placed back in the queue and reprocessed up to 10 times before the batch is permanently marked as failed.
Even if the batch failed, some records could have completed successfully. If you get a timeout error when processing a batch, split your batch into smaller batches, and try again.

To be honest, I'll admit that I probably didn't test particularly large batches (i.e. over the 200 record chunk) when I added support for the bulk operations, and for the usage that I'm actually seeing with this now, it looks like I should probably implement the Composite action which would be a lot of fun...

Have you tried splitting your submission up into batches? You can also query the Job Status via the Workbench and within Salesforce as I recall, and see if there are any obvious errors/warnings that I've missed.

**Comment by StephenDoherty** [comment]
It seems after debugging on the Salesforce side, there were some bad characters in one of the fields that was creating this issue. It just happened to happen at 800 records. I used a regex functions to clean the funky characters out and now it imports all my records in the single batch (957).

` public static string RemoveSpecialCharacters(string str)
 {
            return Regex.Replace(str, "[^a-zA-Z0-9_. ]+", "", RegexOptions.Compiled);
}`

![image](https://user-images.githubusercontent.com/25346980/140079364-102028bd-a06c-4033-a2de-19bca6be1ea1.png)


![image](https://user-images.githubusercontent.com/25346980/140079330-81b875ed-147b-46c7-9f8c-452a5f0f6b55.png)

**Comment by Zhaph** [comment]
Thanks for letting us know, good to know it works nicely ;)
