### ISSUE TITLE
How do we map salesforce object field names to our app?

### ISSUE THREAD

**Issue by v50minasyan** [developerforce/Force.com-Toolkit-for-NET#99]
Dear SalesForce .Net community,
How does the API know what fields are mapped to what? using the field name as object name?

For example,

![image](https://cloud.githubusercontent.com/assets/9093447/6610070/5d9ee54e-c817-11e4-8935-070ca999c243.png)

Where Field Label is Transaction ID
and Field Name is Transaction_TxnID
do I simply do this:   
Transaction_TxnID {get;set;}  
and the API does the rest? Or do I need to go though some other kind of mapping?

**Comment by tomajar** [comment]
Hi @v50minasyan 

Based on the doc: http://www.salesforce.com/us/developer/docs/fundamentals/salesforce_creating_on_demand_apps.pdf

> Note: Within the platform, Field Name is actually stored with __c appended to the end as
a suffix (for example, Job_Description__c). This identifies it as a custom field

>When using fields in formulas, you can't just refer to a field by its name. Instead, you need to refer to it by
its merge field name, also called its API name. The format of the API name is typically the name of the field
but with underscores instead of spaces. For custom fields, the API name is suffixed with two underscores
and the letter “c,” like this: Open_Date__c. This naming convention in the platform helps distinguish
between standard and custom fields.

Look at the test projects, where you have sample queries:

```
 _client.QueryAsync<Account>("SELECT id, name, description FROM Account");
```

But this query is for already existing object on the salesforce platform.

Custom objects have some fields, that are added by default like CreatedDate. They doesn't have the suffix.

If your object is custom, and your field is custom, you probably should have query like

```
_client.QueryAsync<Opportunity>("SELECT Transaction_TxnID__c FROM Opportunity__c");
```

This will fill up your class properties by JSON deserialization.

So I think yes - you should have a class property like:
```
string Transaction_TxnID__c {get;set;}
```

*Just use dynamic type, and see what properties it has ;)*

The other kind of query is using reflection:
```
_client.QueryByIdAsync<Opportunity>("Opportunity__c", id);
```
It will look for all properties in your class:
```
  fields = string.Join(", ", typeof(T).GetRuntimeProperties().Select(p => p.Name));
```

And list them as columns for the select, so your DTO should not have any additional properties. I can consider this behavior as a bug, but you may want to use Automapper to separate the API's dto from your actual logic.

**Comment by wadewegner** [comment]
Thanks for answering, @tomajar!

**Comment by v50minasyan** [comment]
This is pretty cool: - thanks tomajar
  fields = string.Join(", ", typeof(T).GetRuntimeProperties().Select(p => p.Name));
Also, I found the SalesForce developer console to be a big help. When I click browse object there it gives the exact name I was looking for.

**Comment by wadewegner** [comment]
Excellent.
